apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: caddy-scaledobject
  namespace: caddy-demo 
spec:
  scaleTargetRef:
    deploymentName: caddy-deployment
  triggers:
  - type: cpu
    metricType: Utilization 
    metadata:
      type: Utilization 
      value: "30"
  - type: memory
    metricType: Utilization 
    metadata:
      type: Utilization 
      value: "30"
