apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: caddy-scaledobject
  namespace: caddy-demo 
spec:
  minReplicaCount: 1
  maxReplicaCount: 5
  scaleTargetRef:
    name: caddy-deployment
  triggers:
  - type: cpu
    metricType: Utilization 
    metadata:
      value: "70"
  - type: memory
    metricType: Utilization 
    metadata:
      value: "70"
